name: Build Windows
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: windows
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: dtolnay/rust-toolchain@stable
      - run: npm install
      - run: npm run pack
      - uses: actions/upload-artifact@v4
        with:
          name: coucou-windows
          path: windows/release/*
